// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.28.0";

// src/lib/mcp/tools/search-disease-articles.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.28.0";
import { z } from "npm:zod@^4.4.3";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.93.2";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error(
    "SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required"
  );
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/search-disease-articles.ts
var search_disease_articles_default = defineTool({
  name: "search_disease_articles",
  title: "Search disease articles",
  description: "Search published disease articles of the site (section \xAB\u0420\u043E\u0434\u0438\u0442\u0435\u043B\u044F\u043C\xBB) by title, description or keywords.",
  inputSchema: {
    query: z.string().trim().min(2).optional().describe("Search text, e.g. \xAB\u0433\u0438\u043D\u0435\u043A\u043E\u043C\u0430\u0441\u0442\u0438\u044F\xBB."),
    limit: z.number().int().min(1).max(50).default(10).optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let request = supabase.from("disease_articles").select("id, slug, title, description, category, age_group, updated_at").eq("is_published", true).order("sort_order", { ascending: true }).limit(limit ?? 10);
    if (query) {
      const escaped = query.replace(/[%,]/g, " ");
      request = request.or(
        `title.ilike.%${escaped}%,description.ilike.%${escaped}%,keywords.ilike.%${escaped}%`
      );
    }
    const { data, error } = await request;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { articles: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-disease-article.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.28.0";
import { z as z2 } from "npm:zod@^4.4.3";
var get_disease_article_default = defineTool2({
  name: "get_disease_article",
  title: "Get disease article",
  description: "Get the full text of one published disease article by its slug.",
  inputSchema: { slug: z2.string().trim().min(1).describe("Article slug, e.g. \xABginekomastiya\xBB.") },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ slug }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("disease_articles").select("id, slug, title, description, category, age_group, article_content, keywords, updated_at").eq("slug", slug).eq("is_published", true).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) {
      return { content: [{ type: "text", text: `No published article with slug \xAB${slug}\xBB.` }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { article: data }
    };
  }
});

// src/lib/mcp/tools/search-videos.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.28.0";
import { z as z3 } from "npm:zod@^4.4.3";
var search_videos_default = defineTool3({
  name: "search_videos",
  title: "Search videos",
  description: "Search published videos of the video hub by title, summary or tags.",
  inputSchema: {
    query: z3.string().trim().min(2).optional().describe("Search text."),
    rubric: z3.string().trim().min(1).optional().describe("Filter by rubric slug."),
    limit: z3.number().int().min(1).max(50).default(10).optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, rubric, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let request = supabase.from("videos").select("id, slug, title, summary_short, rubric, subrubric, duration_sec, published_at, tags").eq("is_published", true).order("published_at", { ascending: false }).limit(limit ?? 10);
    if (rubric) request = request.eq("rubric", rubric);
    if (query) {
      const escaped = query.replace(/[%,]/g, " ");
      request = request.or(
        `title.ilike.%${escaped}%,summary_short.ilike.%${escaped}%,summary_plain.ilike.%${escaped}%`
      );
    }
    const { data, error } = await request;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { videos: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-blog-posts.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.28.0";
import { z as z4 } from "npm:zod@^4.4.3";
var list_blog_posts_default = defineTool4({
  name: "list_blog_posts",
  title: "List blog posts",
  description: "List published blog posts (\xAB\u0420\u0430\u0437\u043C\u044B\u0448\u043B\u0435\u043D\u0438\u044F\xBB) with excerpts, newest first.",
  inputSchema: {
    query: z4.string().trim().min(2).optional().describe("Optional search text in title or excerpt."),
    limit: z4.number().int().min(1).max(50).default(10).optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let request = supabase.from("blog_posts").select("id, title, excerpt, created_at, updated_at").eq("is_published", true).order("created_at", { ascending: false }).limit(limit ?? 10);
    if (query) {
      const escaped = query.replace(/[%,]/g, " ");
      request = request.or(`title.ilike.%${escaped}%,excerpt.ilike.%${escaped}%`);
    }
    const { data, error } = await request;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { posts: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/search-patients.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.28.0";
import { z as z5 } from "npm:zod@^4.4.3";
var search_patients_default = defineTool5({
  name: "search_patients",
  title: "Search patients",
  description: "Search patient records the signed-in user is allowed to see (access is enforced by database policies).",
  inputSchema: {
    query: z5.string().trim().min(2).describe("Part of the patient name or history number."),
    limit: z5.number().int().min(1).max(25).default(10).optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const escaped = query.replace(/[%,]/g, " ");
    const { data, error } = await supabase.from("patients").select("id, full_name, birth_date, sex, history_number, updated_at").or(`full_name.ilike.%${escaped}%,history_number.ilike.%${escaped}%`).order("updated_at", { ascending: false }).limit(limit ?? 10);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { patients: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-patient-visits.ts
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.28.0";
import { z as z6 } from "npm:zod@^4.4.3";
var list_patient_visits_default = defineTool6({
  name: "list_patient_visits",
  title: "List patient visits",
  description: "List visits (protocols) of one patient the signed-in user may access: date, type, diagnosis, ICD code.",
  inputSchema: {
    patient_id: z6.string().uuid().describe("Patient id returned by search_patients."),
    limit: z6.number().int().min(1).max(50).default(20).optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ patient_id, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("patient_visits").select("id, visit_date, protocol_type, diagnosis, icd_code, next_visit_date, updated_at").eq("patient_id", patient_id).order("visit_date", { ascending: false }).limit(limit ?? 20);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { visits: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "bpbwkizvvythqotcyfii";
var mcp_default = defineMcp({
  name: "tarusin-digital-space",
  title: "Tarusin Digital Space",
  version: "0.1.0",
  instructions: "Tools for Tarusin Digital Space (\u0441\u0430\u0439\u0442 \u043F\u0440\u043E\u0444\u0435\u0441\u0441\u043E\u0440\u0430 \u0422\u0430\u0440\u0443\u0441\u0438\u043D\u0430). Use search_disease_articles / get_disease_article for medical articles, search_videos and list_blog_posts for public content, and search_patients / list_patient_visits for clinical records the signed-in user is allowed to see.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    search_disease_articles_default,
    get_disease_article_default,
    search_videos_default,
    list_blog_posts_default,
    search_patients_default,
    list_patient_visits_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.28.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
