-- Metabolic matrix v2.8: pathway geometry and dependency edges.
-- Additive/idempotent. Existing pathway rules are intentionally preserved.
-- The React SVG cards remain the visual source of truth; nodes/edges are the
-- database fallback for auto-layout, printing and server-side catalog context.

INSERT INTO public.pathways
  (slug, name, description, is_active, nodes, edges, "group", group_order)
VALUES
  ('carbohydrate_pyruvate', 'Пируват–лактат и углеводный обмен', 'Пируват, лактат, аланин', '[{"id":"lactate_u","label":"Молочная кислота (лактат)","x":80,"y":70},{"id":"pyruvate_u","label":"Пировиноградная кислота","x":230,"y":70},{"id":"alanine","label":"Аланин","x":380,"y":70},{"id":"lactate_s","label":"Лактат","x":530,"y":70}]'::jsonb, '[{"from":"alanine","to":"pyruvate_u","label":"реакция"},{"from":"pyruvate_u","to":"lactate_u","label":"реакция"},{"from":"lactate_s","to":"lactate_u","label":"межсредовая пара"}]'::jsonb, 'metabolic_v28', 100),
  ('energy_tca', 'Цикл Кребса и энергообеспечение', 'Интермедиаты ЦТК', '[{"id":"citrate_u","label":"Лимонная кислота","x":80,"y":70},{"id":"cis_aconitate","label":"цис-Аконитовая кислота","x":230,"y":70},{"id":"isocitrate","label":"Изолимонная кислота","x":380,"y":70},{"id":"alpha_ketoglutarate","label":"2-Кетоглутаровая кислота","x":530,"y":70},{"id":"succinate","label":"Янтарная кислота","x":80,"y":160},{"id":"fumarate","label":"Фумаровая кислота","x":230,"y":160},{"id":"malate","label":"Яблочная кислота","x":380,"y":160},{"id":"methylglutarate_2","label":"2-Метилглутаровая кислота","x":530,"y":160}]'::jsonb, '[{"from":"citrate_u","to":"cis_aconitate","label":"реакция"},{"from":"cis_aconitate","to":"isocitrate","label":"реакция"},{"from":"isocitrate","to":"alpha_ketoglutarate","label":"реакция"},{"from":"alpha_ketoglutarate","to":"succinate","label":"реакция"},{"from":"succinate","to":"fumarate","label":"реакция"},{"from":"fumarate","to":"malate","label":"реакция"},{"from":"malate","to":"citrate_u","label":"реакция"},{"from":"succinate","to":"methylglutarate_2","label":"реакция"}]'::jsonb, 'metabolic_v28', 101),
  ('ketogenesis_beta_oxidation', 'Кетогенез и ветвь HMG-CoA', 'Кетоновые и HMG-связанные метаболиты', '[{"id":"hydroxybutyrate_3","label":"3-Гидроксимасляная кислота","x":80,"y":70},{"id":"malonate","label":"Малоновая кислота","x":230,"y":70},{"id":"hydroxy_methylglutarate_3","label":"3-Гидрокси-3-метилглутаровая кислота","x":380,"y":70},{"id":"acetoacetate","label":"Ацетоуксусная кислота (ацетоацетат)","x":530,"y":70}]'::jsonb, '[{"from":"hydroxy_methylglutarate_3","to":"hydroxybutyrate_3","label":"реакция"},{"from":"hydroxy_methylglutarate_3","to":"acetoacetate","label":"реакция"},{"from":"acetoacetate","to":"hydroxybutyrate_3","label":"реакция"}]'::jsonb, 'metabolic_v28', 102),
  ('bcaa_catabolism', 'Катаболизм BCAA', 'Валин, лейцин, изолейцин и их метаболиты', '[{"id":"hydroxy_methylbutyrate_2_3","label":"2-Гидрокси-3-метилбутановая кислота","x":80,"y":70},{"id":"methylcrotonylglycine_3","label":"3-Метилкротонилглицин","x":230,"y":70},{"id":"methylglutarate_3","label":"3-Метилглутаровая кислота","x":380,"y":70},{"id":"isovalerylglycine","label":"Изовалерилглицин","x":530,"y":70},{"id":"methyl_oxovalerate_3","label":"3-Метил-2-оксовалериановая кислота","x":80,"y":160},{"id":"methyl_oxovalerate_4","label":"4-Метил-2-оксовалериановая кислота","x":230,"y":160},{"id":"ketoisovalerate_2","label":"2-Кетоизовалериановая кислота","x":380,"y":160},{"id":"hydroxyisovalerate_3","label":"3-Гидроксиизовалериановая кислота","x":530,"y":160},{"id":"valine","label":"Валин","x":80,"y":250},{"id":"leucine","label":"Лейцин","x":230,"y":250},{"id":"isoleucine","label":"Изолейцин","x":380,"y":250},{"id":"allo_isoleucine","label":"Алло-изолейцин","x":530,"y":250}]'::jsonb, '[{"from":"valine","to":"ketoisovalerate_2","label":"реакция"},{"from":"ketoisovalerate_2","to":"hydroxy_methylbutyrate_2_3","label":"реакция"},{"from":"leucine","to":"methyl_oxovalerate_4","label":"реакция"},{"from":"methyl_oxovalerate_4","to":"isovalerylglycine","label":"реакция"},{"from":"methyl_oxovalerate_4","to":"methylcrotonylglycine_3","label":"реакция"},{"from":"methylcrotonylglycine_3","to":"methylglutarate_3","label":"реакция"},{"from":"methyl_oxovalerate_4","to":"hydroxyisovalerate_3","label":"реакция"},{"from":"isoleucine","to":"methyl_oxovalerate_3","label":"реакция"},{"from":"isoleucine","to":"allo_isoleucine","label":"реакция"}]'::jsonb, 'metabolic_v28', 103),
  ('aromatic_aa_metabolism', 'Фенилаланин и тирозин', 'Ароматические аминокислоты и органические кислоты', '[{"id":"p_hydroxyphenyllactate","label":"пара-Гидроксифенилмолочная кислота","x":80,"y":70},{"id":"p_hydroxyphenylpyruvate","label":"пара-Гидроксифенилпировиноградная кислота","x":230,"y":70},{"id":"homogentisate","label":"Гомогентизиновая кислота","x":380,"y":70},{"id":"phenyllactate","label":"3-Фенилмолочная кислота","x":530,"y":70},{"id":"phenylalanine","label":"Фенилаланин","x":80,"y":160},{"id":"tyrosine","label":"Тирозин","x":230,"y":160}]'::jsonb, '[{"from":"phenylalanine","to":"tyrosine","label":"реакция"},{"from":"tyrosine","to":"p_hydroxyphenylpyruvate","label":"реакция"},{"from":"p_hydroxyphenylpyruvate","to":"homogentisate","label":"реакция"},{"from":"p_hydroxyphenylpyruvate","to":"p_hydroxyphenyllactate","label":"реакция"},{"from":"phenylalanine","to":"phenyllactate","label":"реакция"}]'::jsonb, 'metabolic_v28', 104),
  ('tryptophan_kynurenine', 'Триптофан–кинурениновый путь', 'Триптофан, QUIN, KYNA, XAN, PIC', '[{"id":"quinolinate","label":"Квинолиновая кислота","x":80,"y":70},{"id":"xanthurenate","label":"Ксантуреновая кислота","x":230,"y":70},{"id":"kynurenate","label":"Кинуреновая кислота","x":380,"y":70},{"id":"picolinate","label":"Пиколиновая кислота","x":530,"y":70},{"id":"tryptophan","label":"Триптофан","x":80,"y":160}]'::jsonb, '[{"from":"tryptophan","to":"kynurenate","label":"реакция"},{"from":"tryptophan","to":"xanthurenate","label":"реакция"},{"from":"tryptophan","to":"quinolinate","label":"реакция"},{"from":"quinolinate","to":"picolinate","label":"реакция"}]'::jsonb, 'metabolic_v28', 105),
  ('oxalate_glyoxylate', 'Глиоксилат–оксалат', 'Гликолат, глиоксилат, глицерат, оксалат', '[{"id":"glycolate","label":"Гликолевая кислота","x":80,"y":70},{"id":"glycerate","label":"Глицериновая кислота","x":230,"y":70},{"id":"oxalate","label":"Щавелевая кислота","x":380,"y":70},{"id":"glyoxylate","label":"Глиоксиловая кислота","x":530,"y":70}]'::jsonb, '[{"from":"glycolate","to":"glyoxylate","label":"реакция"},{"from":"glyoxylate","to":"oxalate","label":"реакция"},{"from":"glycerate","to":"glyoxylate","label":"реакция"}]'::jsonb, 'metabolic_v28', 106),
  ('fatty_acid_oxidation', 'Окисление жирных кислот и дикарбоновые кислоты', 'EMA, GA, ADIP, SUBER, SEBAC, MSA', '[{"id":"ethylmalonate","label":"Этилмалоновая кислота","x":80,"y":70},{"id":"methylsuccinate","label":"Метилянтарная кислота","x":230,"y":70},{"id":"glutarate","label":"Глутаровая кислота","x":380,"y":70},{"id":"sebacate","label":"Себациновая кислота","x":530,"y":70},{"id":"adipate","label":"Адипиновая кислота","x":80,"y":160},{"id":"suberate","label":"Субериновая кислота","x":230,"y":160}]'::jsonb, '[]'::jsonb, 'metabolic_v28', 107),
  ('methylation', 'Одноуглеродный обмен и метилирование', 'Метионин, серин/глицин, FIGLU, MMA, SAH', '[{"id":"figlu","label":"Формиминоглутаминовая кислота (FIGLU)","x":80,"y":70},{"id":"methylmalonate","label":"Метилмалоновая кислота","x":230,"y":70},{"id":"sarcosine","label":"Саркозин","x":380,"y":70},{"id":"b12_s","label":"Витамин B12 (кобаламин)","x":530,"y":70},{"id":"folate_s","label":"Фолат","x":80,"y":160}]'::jsonb, '[{"from":"methylmalonate","to":"b12_s","label":"кофактор-ридаут"},{"from":"figlu","to":"folate_s","label":"кофактор-ридаут"}]'::jsonb, 'metabolic_v28', 108),
  ('sulfur_one_carbon', 'Серосодержащие аминокислоты и транссульфурация', 'Метионин, цистатионин, цистин, таурин', '[{"id":"methionine","label":"Метионин","x":80,"y":70},{"id":"taurine","label":"Таурин","x":230,"y":70},{"id":"s_adenosylhomocysteine","label":"S-Аденозилгомоцистеин","x":380,"y":70},{"id":"homocystine","label":"Гомоцистин","x":530,"y":70},{"id":"cystathionine","label":"Цистатионин","x":80,"y":160},{"id":"cysteine_sulfate","label":"Цистеин-сульфат","x":230,"y":160},{"id":"cystine","label":"Цистин","x":380,"y":160},{"id":"homocysteine_s","label":"Гомоцистеин","x":530,"y":160}]'::jsonb, '[{"from":"methionine","to":"s_adenosylhomocysteine","label":"реакция"},{"from":"s_adenosylhomocysteine","to":"homocystine","label":"реакция"},{"from":"homocystine","to":"cystathionine","label":"реакция"},{"from":"cystathionine","to":"cystine","label":"реакция"},{"from":"cystathionine","to":"cysteine_sulfate","label":"реакция"},{"from":"cysteine_sulfate","to":"taurine","label":"реакция"},{"from":"homocystine","to":"methionine","label":"межпутевая"},{"from":"s_adenosylhomocysteine","to":"homocysteine_s","label":"реакция"},{"from":"homocysteine_s","to":"cystathionine","label":"реакция"},{"from":"homocysteine_s","to":"homocystine","label":"реакция"}]'::jsonb, 'metabolic_v28', 109),
  ('glutathione_detox', 'γ-Глутамильный цикл и глутатион', 'Пироглутамат, 2-гидроксибутират и аминокислотные субстраты', '[{"id":"hydroxybutyrate_2","label":"2-Гидроксимасляная кислота","x":80,"y":70},{"id":"pyroglutamate","label":"Пироглутаминовая кислота (5-оксопролин)","x":230,"y":70}]'::jsonb, '[]'::jsonb, 'metabolic_v28', 110),
  ('amino_urea', 'Цикл мочевины и оротатная ветвь', 'Аргинин, орнитин, цитруллин, аргининосукцинат, аспартат, оротат', '[{"id":"orotate","label":"Оротовая кислота","x":80,"y":70},{"id":"arginine","label":"Аргинин","x":230,"y":70},{"id":"aspartate","label":"Аспарагиновая кислота","x":380,"y":70},{"id":"argininosuccinate","label":"Аргининоянтарная кислота","x":530,"y":70},{"id":"homocitrulline","label":"Гомоцитруллин","x":80,"y":160},{"id":"ornithine","label":"Орнитин","x":230,"y":160},{"id":"citrulline","label":"Цитруллин","x":380,"y":160}]'::jsonb, '[{"from":"ornithine","to":"citrulline","label":"реакция"},{"from":"citrulline","to":"argininosuccinate","label":"реакция"},{"from":"argininosuccinate","to":"arginine","label":"реакция"},{"from":"arginine","to":"ornithine","label":"реакция"},{"from":"aspartate","to":"argininosuccinate","label":"реакция"},{"from":"citrulline","to":"orotate","label":"реакция"},{"from":"ornithine","to":"homocitrulline","label":"реакция"}]'::jsonb, 'metabolic_v28', 111),
  ('amino_nitrogen_exchange', 'Обмен аминного азота', 'Глутамат, глутамин, аспарагин, аспартат, 2-оксоглутарат', '[{"id":"asparagine","label":"Аспарагин","x":80,"y":70},{"id":"glutamine","label":"Глутамин","x":230,"y":70},{"id":"glutamate","label":"Глутаминовая кислота","x":380,"y":70}]'::jsonb, '[{"from":"glutamate","to":"glutamine","label":"реакция"}]'::jsonb, 'metabolic_v28', 112),
  ('glycine_serine_threonine', 'Обмен глицина, серина и треонина', 'Глицин, серин, треонин', '[{"id":"threonine","label":"Треонин","x":80,"y":70},{"id":"glycine","label":"Глицин","x":230,"y":70},{"id":"serine","label":"Серин","x":380,"y":70}]'::jsonb, '[{"from":"threonine","to":"glycine","label":"реакция"},{"from":"serine","to":"glycine","label":"реакция"}]'::jsonb, 'metabolic_v28', 113),
  ('lysine_catabolism', 'Катаболизм лизина', 'Лизин, сахаропин, аминоадипат, пипеколат', '[{"id":"lysine","label":"Лизин","x":80,"y":70},{"id":"aminoadipate_alpha","label":"Альфа-аминоадипиновая кислота","x":230,"y":70},{"id":"pipecolate","label":"Пипеколиновая кислота","x":380,"y":70},{"id":"saccharopine","label":"Сахаропин","x":530,"y":70}]'::jsonb, '[{"from":"lysine","to":"saccharopine","label":"реакция"},{"from":"saccharopine","to":"aminoadipate_alpha","label":"реакция"},{"from":"lysine","to":"pipecolate","label":"реакция"}]'::jsonb, 'metabolic_v28', 114),
  ('collagen_turnover', 'Коллагеновый обмен', 'Пролин, гидроксипролин, гидроксилизин, глицин', '[{"id":"proline","label":"Пролин","x":80,"y":70},{"id":"hydroxylysine","label":"Гидроксилизин","x":230,"y":70},{"id":"hydroxyproline_4","label":"4-Гидроксипролин","x":380,"y":70}]'::jsonb, '[{"from":"proline","to":"hydroxyproline_4","label":"реакция"}]'::jsonb, 'metabolic_v28', 115),
  ('histidine_muscle_turnover', 'Гистидин и мышечные дипептиды', 'Гистидин, метилгистидины, карнозин, ансерин', '[{"id":"histidine","label":"Гистидин","x":80,"y":70},{"id":"methylhistidine_1","label":"1-Метилгистидин","x":230,"y":70},{"id":"methylhistidine_3","label":"3-Метилгистидин","x":380,"y":70},{"id":"anserine","label":"Ансерин","x":530,"y":70},{"id":"carnosine","label":"Карнозин","x":80,"y":160}]'::jsonb, '[{"from":"carnosine","to":"histidine","label":"реакция"},{"from":"anserine","to":"methylhistidine_1","label":"реакция"},{"from":"histidine","to":"methylhistidine_3","label":"реакция"}]'::jsonb, 'metabolic_v28', 116),
  ('beta_alanine_metabolism', 'Обмен β-аланина', 'β-Аланин и связанные метаболиты', '[{"id":"beta_alanine","label":"Бета-аланин","x":80,"y":70}]'::jsonb, '[]'::jsonb, 'metabolic_v28', 117),
  ('glycerophospholipid_amines', 'Аминоспирты глицерофосфолипидов', 'Фосфосерин, фосфоэтаноламин, этаноламин', '[{"id":"phosphoserine","label":"Фосфосерин","x":80,"y":70},{"id":"phosphoethanolamine","label":"Фосфоэтаноламин","x":230,"y":70},{"id":"ethanolamine","label":"Этаноламин","x":380,"y":70}]'::jsonb, '[{"from":"phosphoserine","to":"phosphoethanolamine","label":"реакция"},{"from":"phosphoethanolamine","to":"ethanolamine","label":"реакция"}]'::jsonb, 'metabolic_v28', 118),
  ('omega3_pufa', 'Омега-3 ПНЖК (АЛК, ЭПК, ДГК)', 'АЛК, ЭПК, ДГК', '[{"id":"ala","label":"Альфа-линоленовая кислота","x":80,"y":70},{"id":"epa","label":"Эйкозапентаеновая кислота","x":230,"y":70},{"id":"dha","label":"Докозагексаеновая кислота","x":380,"y":70}]'::jsonb, '[{"from":"ala","to":"epa","label":"реакция"},{"from":"epa","to":"dha","label":"реакция"}]'::jsonb, 'metabolic_v28', 119),
  ('omega6_pufa', 'Омега-6 ПНЖК', 'Линолевая, GLA, DGLA, арахидоновая', '[{"id":"linoleic","label":"Линолевая кислота","x":80,"y":70},{"id":"gla","label":"Гамма-линоленовая кислота","x":230,"y":70},{"id":"dgla","label":"Дигомо-гамма-линоленовая кислота","x":380,"y":70},{"id":"arachidonic","label":"Арахидоновая кислота","x":530,"y":70},{"id":"eicosadienoic","label":"Эйкозадиеновая кислота","x":80,"y":160},{"id":"docosadienoic","label":"Докозадиеновая кислота","x":230,"y":160},{"id":"dta","label":"Докозатетраеновая кислота","x":380,"y":160}]'::jsonb, '[{"from":"linoleic","to":"gla","label":"реакция"},{"from":"gla","to":"dgla","label":"реакция"},{"from":"dgla","to":"arachidonic","label":"реакция"},{"from":"arachidonic","to":"dta","label":"реакция"},{"from":"linoleic","to":"eicosadienoic","label":"реакция"},{"from":"eicosadienoic","to":"docosadienoic","label":"реакция"}]'::jsonb, 'metabolic_v28', 120),
  ('omega9_mufa', 'Омега-9 МНЖК', 'Олеиновая, мидовая, нервоновая', '[{"id":"hexadecenoic_n9","label":"Гексадеценовая кислота C16:1ω9","x":80,"y":70},{"id":"mead","label":"Мидовая кислота","x":230,"y":70},{"id":"oleic","label":"Олеиновая кислота","x":380,"y":70},{"id":"nervonic","label":"Селахолевая (нервоновая) кислота","x":530,"y":70}]'::jsonb, '[{"from":"oleic","to":"mead","label":"реакция"}]'::jsonb, 'metabolic_v28', 121)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  is_active = true,
  nodes = EXCLUDED.nodes,
  edges = EXCLUDED.edges,
  "group" = EXCLUDED."group",
  group_order = EXCLUDED.group_order,
  updated_at = now();

-- Do not insert severity rules here: the clinical matrix explicitly marks
-- these v2.8 pathway cards as context/display-only until separate rules are
-- approved by the physician.
